// Ophelia Intelligent Agent — continuous screen-aware browser co-pilot
// Ctrl+Shift+U → goal dialog → screenshot + DOM → Claude → next step → highlight → wait → repeat
// Multi-turn conversation: Claude remembers what's been done and adapts to page changes.
window.OpheliaAssistant = (() => {
  // 4 messages = 2 full turns. Images stripped from all but latest → ~$0.005-0.008/step.
  const MAX_HISTORY = 12;

  let _goal      = '';
  let _messages  = []; // multi-turn conversation history
  let _active    = false;
  let _stepCount = 0;
  let _waitingForAction = false;
  let _cleanupFns = []; // teardown callbacks for event listeners / timers
  let _highlightedEl = null;
  let _ttsRate        = 1.05; // loaded from chrome.storage.sync on session start
  let _pendingResume      = null;  // {goal, stepCount} waiting for Ctrl+Space confirmation
  let _resumeTimer        = null;  // auto-discard timeout
  let _checkObstacleNext  = true;  // run obstacle check on first step and after each navigation
  let _plan     = [];  // ordered step list generated by plan_session at session start
  let _planStep = 0;   // current step index (informational — Claude reads the plan)

  // ── 5C: Step verification ─────────────────────────────────────────────────────
  let _preClickSnapshot = null;  // DOM snapshot captured just before the user clicks
  let _lastStepFailed   = false; // true when DOM didn't change after last click

  // ── Element refs (index-based matching) ──────────────────────────────────
  let _scannedRefs = []; // real DOM element refs from last _scanPage() call

  // ── Screenshot cache ─────────────────────────────────────────────────
  let _lastPageKey    = '';   // "href|scrollBucket" of last capture
  let _lastScreenshot = null; // base64 of last capture (reused on cache hit)
  let _stepsSinceNav  = 0;    // steps taken on the current URL (drives quality decay)

  // ── Mic state ────────────────────────────────────────────────────────────────
  let _mic              = null;  // active SpeechRecognition instance
  let _micActive        = false; // true while recording
  let _micFinalText     = '';    // accumulated final transcript
  let _micCallback      = null;  // called with final text on _stopMic()

  // ── Public API ─────────────────────────────────────────────────────────────

  function activate() {
    // If mic is open: second press commits the recording
    if (_micActive) { _stopMic(); return; }

    // If a cross-page resume is pending, Ctrl+Space = confirm resume
    if (_pendingResume) {
      clearTimeout(_resumeTimer);
      const { goal, stepCount } = _pendingResume;
      _pendingResume = null;
      _clearDotLabel();
      _goal = goal; _stepCount = stepCount; _messages = []; _active = true;
      _watchPage();
      _analyze('Resuming previous session. What is the next step toward the goal?');
      return;
    }

    if (_active) {
      // Session running: let user correct or ask via voice
      _listenForMessage();
    } else {
      if (window.opheliaTutorialActive) window.OpheliaPlayer?.stop();
      _listenForGoal();
    }
  }

  async function checkResume() {
    if (_active) return;
    try {
      const { opheliaSession } = await chrome.storage.session.get('opheliaSession');
      if (!opheliaSession?.goal) return;
      _pendingResume = opheliaSession;
      _setDotLabel('🔄 Resume? Ctrl+Space');
      _speak(`Resume "${opheliaSession.goal}"? Press Ctrl+Space to continue.`);
      _resumeTimer = setTimeout(() => {
        _pendingResume = null;
        _clearDotLabel();
      }, 10000);
    } catch (_) {}
  }

  function stop() {
    _stopMic();  // kill any open mic first
    _active = false;
    _waitingForAction = false;
    _cleanupFns.forEach(fn => fn());
    _cleanupFns = [];
    _clearHighlight();
    _clearDotLabel();
    window.speechSynthesis?.cancel();
    _goal = ''; _messages = []; _stepCount = 0; _plan = []; _planStep = 0;
    clearTimeout(_resumeTimer);
    _pendingResume = null;
    chrome.storage.session.remove('opheliaSession').catch(() => {});
  }

  function isActive() { return _active; }

  // ── Persistent toggle-mic ───────────────────────────────────────────────────
  // First Ctrl+Shift+U → starts recording (continuous, shows live transcript).
  // Second Ctrl+Shift+U → commits text and processes it.

  function _startMic(callback) {
    const SR = window.SpeechRecognition || window.webkitSpeechRecognition;
    if (!SR) { _showTextFallback(callback); return; }

    _micCallback  = callback;
    _micFinalText = '';
    _micActive    = true;
    _setDotLabel('🔴 Listening…  (press Ctrl+Shift+U to send)');

    // Sphere → red glow (per MECHANISM_RULES)
    const sphere = document.getElementById('cross-tab-sphere');
    if (sphere) {
      sphere.style.background  = '#ff2222';
      sphere.style.boxShadow   = '0 0 20px #ff0000, 0 0 40px rgba(255,0,0,0.4)';
    }

    _mic = new SR();
    _mic.lang            = 'en-US';
    _mic.continuous      = true;   // keep open until _stopMic()
    _mic.interimResults  = true;

    _mic.onresult = (e) => {
      // Accumulate final segments; show live interim text in label
      let interim = '';
      for (let i = e.resultIndex; i < e.results.length; i++) {
        if (e.results[i].isFinal) {
          _micFinalText += e.results[i][0].transcript + ' ';
        } else {
          interim += e.results[i][0].transcript;
        }
      }
      const preview = (_micFinalText + interim).trim().slice(-60);
      _setDotLabel(`🔴 ${preview || 'Listening…'}`);
    };

    _mic.onerror = (err) => {
      if (err.error === 'not-allowed') { _micActive = false; _mic = null; _clearDotLabel(); }
      // other errors (network, aborted): ignore — onend will restart if still active
    };

    // Chrome kills continuous sessions after ~60 s of silence → restart transparently
    _mic.onend = () => {
      if (_micActive && _mic) {
        try { _mic.start(); } catch (_) {}
      }
    };

    _mic.start();
  }

  function _stopMic() {
    if (!_micActive) return;
    _micActive = false;
    if (_mic) {
      _mic.onend = null; // prevent restart loop
      try { _mic.stop(); } catch (_) {}
      _mic = null;
    }
    _clearDotLabel();

    // Sphere → orange (inactive state)
    const sphere = document.getElementById('cross-tab-sphere');
    if (sphere) {
      sphere.style.background = '#ff7a1a';
      sphere.style.boxShadow  = '0 0 16px #ff7a1a';
    }

    const text = _micFinalText.trim();
    _micFinalText = '';
    const cb = _micCallback;
    _micCallback = null;
    if (text && cb) cb(text);
  }

  // ── Goal / message listeners ────────────────────────────────────────────────

  function _listenForGoal() {
    _startMic(async (goal) => {
      const check = await _clarifyGoal(goal);
      if (check.clear) {
        _startSession(goal);
      } else {
        // Speak the question, then reopen mic once TTS finishes
        _speak(check.question, () => {
          _setDotLabel('🔴 Listening…  (press Ctrl+Space to send)');
          _startMic((refined) => _startSession(refined || goal));
        });
      }
    });
  }

  async function _clarifyGoal(goal) {
    _setDotLabel('Thinking…');
    return new Promise(resolve => {
      chrome.runtime.sendMessage({ action: 'clarifyGoal', goal }, result => {
        if (chrome.runtime.lastError || !result) {
          console.warn('⚠️ _clarifyGoal SW error, proceeding directly');
          resolve({ clear: true });
        } else {
          resolve(result);
        }
      });
    });
  }

  function _listenForMessage() {
    _startMic((text) => _userMessage(text));
  }

  // ── Session start ───────────────────────────────────────────────────────────

  async function _startSession(goal) {
    _goal = goal;
    _messages = [];
    _active = true;
    _stepCount = 0;
    _lastPageKey = ''; _lastScreenshot = null; _stepsSinceNav = 0;
    _checkObstacleNext = true;
    _plan = []; _planStep = 0;

    // Load persisted TTS rate preference
    try {
      const s = await chrome.storage.sync.get('ttsRate');
      if (typeof s.ttsRate === 'number') _ttsRate = s.ttsRate;
    } catch (_) {}

    // Generate a session plan before first analysis (gives Claude step-level coherence)
    _setDotLabel('Planning…');
    const planScreenshot = await _captureScreen(); // visual context for the planner
    _plan = await _planSession(planScreenshot);
    if (_plan.length) console.log('\uD83D\uDCCB Session plan:', _plan);

    _watchPage();
    await _analyze('What is the first step the user should take?');
  }

  // ── Core analysis loop ──────────────────────────────────────────────────────
  // Called after every user action, navigation, or explicit message.

  async function _analyze(trigger, _retries = 0) {
    if (!_active) return;
    _waitingForAction = false;
    _clearHighlight();

    _setDotLabel('Thinking…');

    // 1. Take screenshot (visual context)
    const screenshot = await _captureScreen();

    // 1.5 Obstacle check (first step + after navigation only — lightweight, no DOM)
    if (_checkObstacleNext) {
      _checkObstacleNext = false;
      if (screenshot) {
        const obs = await _checkObstacle(screenshot);
        if (obs) {
          _speak(obs.action);
          _setDotLabel(`⚠️ ${obs.action}`);
          _waitingForAction = true;
          return; // user dismisses obstacle → next click re-triggers _analyze
        }
      }
    }

    // 2. Scan DOM
    const dom   = _scanPage();
    const elStr = _formatElements(dom.elements);

    // 3. Build this turn's user message (image + text)
    const userContent = [];
    if (screenshot) {
      userContent.push({
        type: 'image',
        source: { type: 'base64', media_type: 'image/jpeg', data: screenshot }
      });
    }
    userContent.push({
      type: 'text',
      text: `Goal: "${_goal}"\nPage: ${dom.url}\nTitle: ${dom.title}\n\nInteractive elements:\n${elStr}\n\n${trigger}`
    });

    // Store text-only copy in history (strip image from older turns to save tokens)
    _messages.push({ role: 'user', content: userContent });

    // 4. Call Claude (with trimmed history)
    const step = await _callClaude();

    if (!step) {
      _setDotLabel('No response — try again.');
      _waitingForAction = true;
      return;
    }

    // Store assistant reply in history
    _messages.push({ role: 'assistant', content: step._raw });

    // Trim history to MAX_HISTORY messages (keep token cost bounded)
    if (_messages.length > MAX_HISTORY) {
      _messages = _messages.slice(_messages.length - MAX_HISTORY);
    }

    _stepCount++;
    // Persist session for cross-page resume (goal only — messages reset on new page)
    chrome.storage.session.set({ opheliaSession: { goal: _goal, stepCount: _stepCount } }).catch(() => {});

    // 5a. Goal complete
    if (step.done) {
      _speak('Done! Your goal is complete.');
      _setDotLabel('✅ Done!');
      setTimeout(stop, 4000);
      return;
    }

    // 5b. Show next step
    const el = await _resolveEl(step, screenshot);

    if (!el && typeof step.elementIndex === 'number' && _retries < 2) {
      _messages.push({
        role: 'user',
        content: [{ type: 'text', text:
          `Element at index ${step.elementIndex} was not found (the DOM may have changed). ` +
          `Re-examine the screenshot and DOM list and choose a different elementIndex or set elementIndex to null.`
        }]
      });
      console.warn(`⚠️ _resolveEl failed (retry ${_retries + 1}/2)`);
      setTimeout(() => { if (_active) _analyze('Element not found, re-examining.', _retries + 1); }, 1200);
      return;
    }

    if (!step._instructionSpoken) _speak(step.instruction);

    if (el) {
      // Instant scroll so getBoundingClientRect is correct immediately.
      // Double-rAF ensures the browser has finished layout before we read positions.
      el.scrollIntoView({ behavior: 'instant', block: 'center' });
      requestAnimationFrame(() => requestAnimationFrame(() => {
        if (_active) _highlightElement(el);
      }));
    } else {
      _setDotLabel(`Step ${_stepCount}`);
    }

    _waitingForAction = true;
  }

  // ── 5C: DOM snapshot for step verification ──────────────────────────────────

  function _domSnapshot() {
    const interactiveCount = document.querySelectorAll(
      'button, a[href], input, select, textarea, [role="button"], [role="link"], [role="menuitem"], [role="option"]'
    ).length;
    const hasModal = !!(
      document.querySelector('[role="dialog"]') ||
      document.querySelector('[aria-modal="true"]') ||
      document.querySelector('.modal, .popup')
    );
    return { url: location.href, elementCount: interactiveCount, hasModal, scrollY: Math.round(window.scrollY) };
  }

  function _snapshotChanged(before, after) {
    if (!before) return true;
    if (before.url !== after.url) return true;
    if (before.hasModal !== after.hasModal) return true;
    if (Math.abs(before.elementCount - after.elementCount) > 2) return true;
    return false;
  }

  // ── Page watcher ────────────────────────────────────────────────────────────
  // Re-analyzes after any user click or URL change.

  function _watchPage() {
    let lastUrl = location.href;
    let debounceTimer = null;

    const reanalyze = (trigger, skipVerify = false) => {
      clearTimeout(debounceTimer);
      debounceTimer = setTimeout(() => {
        if (!_active) return;
        if (!skipVerify && _preClickSnapshot) {
          const after = _domSnapshot();
          _lastStepFailed = !_snapshotChanged(_preClickSnapshot, after);
          _preClickSnapshot = null;
          if (_lastStepFailed) console.warn('⚠️ Step verification: DOM unchanged after click — step may have failed');
        }
        _analyze(trigger);
      }, 900);
    };

    const onClick = (e) => {
      if (!_active || !_waitingForAction) return;
      // Ignore clicks on our own panel
      if (e.target.closest('#ophelia-fallback')) return;
      _clearHighlight();
      _setDotLabel('Processing…');
      _lastPageKey    = '';   // force fresh screenshot — SPA tab switches don't change URL
      _preClickSnapshot = _domSnapshot();
      reanalyze('User just performed an action. What is the next step toward the goal?');
    };

    const navPoll = setInterval(() => {
      if (!_active) { clearInterval(navPoll); return; }
      if (location.href !== lastUrl) {
        lastUrl = location.href;
        _preClickSnapshot  = null;   // navigation = click clearly worked
        _lastStepFailed    = false;
        _checkObstacleNext = true;
        _setDotLabel('Page changed…');
        reanalyze('User navigated to a new page. What is the next step toward the goal?', true);
      }
    }, 300);

    document.addEventListener('click', onClick, true);
    _cleanupFns.push(
      () => document.removeEventListener('click', onClick, true),
      () => clearInterval(navPoll)
    );
  }

  // ── User sends a message from the Ask field ─────────────────────────────────

  function _userMessage(text) {
    if (!_active) return;
    _clearHighlight();
    _setDotLabel('Processing…');
    _analyze(`User says: "${text}". Take this into account for the next step.`);
  }

  function _skip() {
    if (!_active) return;
    _analyze('User skipped this step. What is the next step toward the goal?');
  }

  // ── Screenshot (with pageKey cache + adaptive JPEG quality) ────────────────────
  // Cache hit:  same URL + same 50px scroll bucket → return previous base64 (no network call)
  // Quality:    URL just changed → 75% | 0–1 steps on page → 70% | 2+ steps → 50%

  function _captureScreen() {
    // Round scrollY to 50px buckets — minor scroll jitter shouldn't bust the cache
    const pageKey = `${location.href}|${Math.round(window.scrollY / 50) * 50}`;

    // Cache hit: page hasn't meaningfully changed
    if (pageKey === _lastPageKey && _lastScreenshot) {
      console.log('📷 Screenshot cache hit');
      return Promise.resolve(_lastScreenshot);
    }

    // Detect navigation: href differs from what was cached
    const urlChanged = !!_lastPageKey && !_lastPageKey.startsWith(location.href + '|');
    if (urlChanged) _stepsSinceNav = 0;

    // Adaptive quality: high after nav, normal early-page, reduced once page is stable
    const quality = urlChanged ? 75 : (_stepsSinceNav >= 2 ? 50 : 70);

    _lastPageKey = pageKey;
    _stepsSinceNav++;
    console.log(`📷 Capturing screenshot — quality ${quality}%, stepsSinceNav ${_stepsSinceNav}`);

    return new Promise(resolve => {
      try {
        chrome.runtime.sendMessage({ action: 'captureTab', quality }, res => {
          if (chrome.runtime.lastError) { resolve(null); return; }
          const url = res?.dataUrl || null;
          const b64 = url ? url.replace(/^data:image\/[a-z]+;base64,/, '') : null;
          _lastScreenshot = b64;
          resolve(b64);
        });
      } catch (_) { resolve(null); }
    });
  }

  // ── Page scanning ───────────────────────────────────────────────────────────

  function _scanPage() {
    const SEL = [
      'button', 'a[href]', 'input', 'select', 'textarea',
      '[role="button"]', '[role="link"]', '[role="menuitem"]',
      '[role="option"]', '[role="tab"]', '[role="checkbox"]',
      '[role="switch"]', '[role="radio"]', '[aria-label]', '[data-testid]'
    ].join(',');

    const vw = window.innerWidth, vh = window.innerHeight;
    const combined = []; // {el, dist, data} — sorted by proximity to viewport center
    const seen = new Set();
    _scannedRefs = []; // reset refs for this scan

    document.querySelectorAll(SEL).forEach(el => {
      const r  = el.getBoundingClientRect();
      const cs = window.getComputedStyle(el);
      if (cs.display === 'none' || cs.visibility === 'hidden') return;
      if (parseFloat(cs.opacity) === 0 || r.width === 0 || r.height === 0) return;
      // Capture viewport + generous scroll buffer (sidebar menus, below-fold nav)
      if (r.bottom < -500 || r.top > vh + 1500 || r.right < 0 || r.left > vw + 300) return;

      const aria    = el.getAttribute('aria-label') || '';
      const testId  = el.getAttribute('data-testid') || '';
      const ownText = [...el.childNodes]
        .filter(n => n.nodeType === Node.TEXT_NODE)
        .map(n => n.textContent.trim()).filter(Boolean)
        .join(' ').replace(/\s+/g, ' ').substring(0, 40);
      const fullText = (el.textContent || '').trim().replace(/\s+/g, ' ').substring(0, 40);
      const text  = ownText || fullText;
      const label = aria || testId || text || '';
      if (!label) return;

      const key = `${label.toLowerCase().substring(0, 30)}|${el.tagName}`;
      if (seen.has(key)) return;
      seen.add(key);

      const cx = r.left + r.width / 2, cy = r.top + r.height / 2;
      const hR = cx < vw / 3 ? 'left'   : cx < 2 * vw / 3 ? 'center'  : 'right';
      const vR = cy < 0      ? 'above'  : cy < vh / 3      ? 'top'     :
                 cy < 2*vh/3 ? 'mid'    : cy < vh           ? 'bottom'  : 'below';

      // Distance from viewport center — elements fully in view rank first
      const dist = Math.abs(cy - vh / 2) + Math.abs(cx - vw / 2) * 0.3;

      combined.push({
        el,
        dist,
        data: {
          tag:          el.tagName.toLowerCase(),
          role:         el.getAttribute('role') || el.computedRole || null,
          aria_label:   aria || el.computedLabel || null,
          data_testid:  testId || null,
          text_content: ownText || null,
          label,
          position:     `${vR}-${hR}`,
          disabled:     el.disabled || el.getAttribute('aria-disabled') === 'true' || null,
          expanded:     el.getAttribute('aria-expanded') || null,
          required:     el.required || el.getAttribute('aria-required') === 'true' || null
        }
      });
    });

    // Sort: closest to viewport center first (most relevant to user's current focus)
    combined.sort((a, b) => a.dist - b.dist);
    const top = combined.slice(0, 80);
    _scannedRefs = top.map(c => c.el);
    const elements = top.map(c => c.data);

    return { url: location.href, title: document.title, elements };
  }

  // ── Obstacle detector (pre-flight, now handled by SW) ──────────────────────

  async function _checkObstacle(screenshot) {
    return new Promise(resolve => {
      chrome.runtime.sendMessage({ action: 'checkObstacle', screenshot }, result => {
        resolve(chrome.runtime.lastError ? null : (result || null));
      });
    });
  }

  // ── Claude call (4A: delegates to SW via sendMessage) ──────────────────────

  async function _callClaude() {
    // Strip images from older turns before sending to SW (keeps IPC payload small)
    const apiMessages = _messages.map((m, i) => {
      const isLastUser = m.role === 'user' && i === _messages.length - 1;
      if (!isLastUser && Array.isArray(m.content)) {
        const textParts = m.content.filter(c => c.type === 'text');
        const hadImage  = m.content.some(c => c.type === 'image');
        return {
          role: m.role,
          content: hadImage
            ? [{ type: 'text', text: '[screenshot from previous step]' }, ...textParts]
            : textParts
        };
      }
      return { role: m.role, content: m.content };
    });

    const stepFailed   = _lastStepFailed;
    _lastStepFailed     = false;
    return new Promise(resolve => {
      chrome.runtime.sendMessage(
        { action: 'analyze', apiMessages, language: navigator.language || 'en', plan: _plan, pageUrl: location.href, stepFailed },
        step => {
          if (chrome.runtime.lastError) {
            console.error('\u274c SW analyze error:', chrome.runtime.lastError.message);
            resolve(null);
          } else {
            resolve(step || null);
          }
        }
      );
    });
  }

  // ── Element resolver — index-based direct lookup + coord fallback ─────────────

  async function _resolveEl(step, screenshot) {
    const i = step.elementIndex;

    // Primary: direct ref by index — O(1), no matching
    if (typeof i === 'number' && _scannedRefs[i]) {
      const el = _scannedRefs[i];
      if (document.contains(el)) {
        console.log(`✅ _resolveEl: direct ref #${i}`);
        return el;
      }
      console.warn(`⚠️ _resolveEl: ref #${i} stale (React re-render?), trying coord fallback`);
    }

    // Fallback: coord lookup via screenshot (Haiku looks at screenshot and returns x,y)
    if (screenshot) {
      const label = step.instruction || (typeof i === 'number' ? `element #${i}` : null);
      if (label) {
        try {
          const coords = await new Promise(resolve => {
            chrome.runtime.sendMessage({ action: 'coordLookup', screenshot, label }, res => {
              resolve(chrome.runtime.lastError ? null : res);
            });
          });
          if (coords) {
            const dpr  = window.devicePixelRatio || 1;
            const cssX = Math.round(coords.x / dpr), cssY = Math.round(coords.y / dpr);
            const hit  = document.elementFromPoint(cssX, cssY);
            if (hit && hit !== document.body && hit !== document.documentElement) {
              console.log(`✅ _resolveEl: coord fallback at CSS ${cssX},${cssY}`);
              return hit;
            }
          }
        } catch (_) {}
      }
    }

    console.log(`❌ _resolveEl: no element found (index=${i})`);
    return null;
  }

  // ── Element highlight — delegates to OpheliaOverlay (same as tutorial player) ─

  function _highlightElement(el) {
    _clearHighlight();
    if (!el) return;
    _highlightedEl = el;
    _clearDotLabel(); // label not needed when dot is on the element

    try {
      window.OpheliaOverlay.show({
        stepNumber: _stepCount,
        totalSteps: _stepCount + 1,
        instruction: '',
        element: el,
        onCorrect: null
      });
      document.getElementById('ophelia-card')?.remove();
    } catch (e) {
      console.warn('OpheliaOverlay unavailable, using fallback highlight', e);
      _applyFallbackHighlight(el);
      return;
    }

    // Re-pin dot after any late layout shifts (e.g. sticky headers, animations)
    setTimeout(() => {
      const dot = document.getElementById('ophelia-dot');
      if (!dot || !_highlightedEl) return;
      const r = _highlightedEl.getBoundingClientRect();
      if (r.width > 0 && r.height > 0) {
        dot.style.left = `${r.left + r.width  / 2}px`;
        dot.style.top  = `${r.top  + r.height / 2}px`;
      }
    }, 250);
  }

  function _applyFallbackHighlight(el) {
    // Pure CSS fallback when OpheliaOverlay is not available
    if (!document.getElementById('ophelia-fb-css')) {
      const s = document.createElement('style');
      s.id = 'ophelia-fb-css';
      s.textContent = `
        .ophelia-fb-target {
          outline: 3px solid #ff7a1a !important;
          outline-offset: 4px !important;
          box-shadow: 0 0 0 6px rgba(255,122,26,0.3) !important;
        }`;
      document.head.appendChild(s);
    }
    el.classList.add('ophelia-fb-target');
    // Create a dot manually
    const r   = el.getBoundingClientRect();
    const dot = document.createElement('div');
    dot.id = 'ophelia-dot';
    dot.style.cssText = [
      'position:fixed', `left:${r.left + r.width/2}px`, `top:${r.top + r.height/2}px`,
      'width:18px','height:18px','background:#ff7a1a','border-radius:50%',
      'transform:translate(-50%,-50%)','z-index:2147483647','pointer-events:none',
      'animation:opheliaDotPulse 1.2s ease-in-out infinite'
    ].join(';');
    document.body.appendChild(dot);
  }

  function _clearHighlight() {
    try { window.OpheliaOverlay.hide(); } catch (_) {}
    // Also clean up any fallback highlight
    document.getElementById('ophelia-dot')?.remove();
    document.querySelectorAll('.ophelia-fb-target').forEach(e => e.classList.remove('ophelia-fb-target'));
    _highlightedEl = null;
  }

  // ── Element format ──────────────────────────────────────────────────────────

  function _formatElements(elements) {
    return elements.map((e, i) => {
      const obj = { tag: e.tag };
      if (e.aria_label)   obj.aria_label   = e.aria_label;
      if (e.text_content) obj.text_content = e.text_content;
      if (e.role)         obj.role         = e.role;
      if (e.data_testid)  obj.data_testid  = e.data_testid;
      if (e.disabled)     obj.disabled     = true;
      if (e.expanded)     obj.expanded     = e.expanded;
      if (e.required)     obj.required     = true;
      return `[${String(i).padStart(2)}] @${e.position}  ${JSON.stringify(obj)}`;
    }).join('\n');
  }

  // ── Element inspector (4B tool: inspect_element) ────────────────────────

  function _inspectElement(hint) {
    const nHint = (hint || '').trim().toLowerCase();
    const SEL = [
      'button', 'a[href]', 'input', 'select', 'textarea',
      '[role="button"]', '[role="link"]', '[aria-label]', '[data-testid]'
    ].join(',');

    let best = null, bestScore = 0;
    document.querySelectorAll(SEL).forEach(el => {
      const candidates = [
        el.getAttribute('aria-label'),
        el.getAttribute('data-testid'),
        (el.textContent || '').trim().slice(0, 60),
        el.getAttribute('placeholder')
      ].filter(Boolean).map(s => s.toLowerCase());

      const score = candidates.reduce((max, c) => {
        if (c === nHint)                              return Math.max(max, 100);
        if (c.includes(nHint) || nHint.includes(c))  return Math.max(max, 50);
        return max;
      }, 0);
      if (score > bestScore) { bestScore = score; best = el; }
    });

    if (!best) return { found: false, hint };

    const cs   = window.getComputedStyle(best);
    const form = best.closest('form');
    const missingRequired = form
      ? [...form.elements]
          .filter(f => (f.required || f.getAttribute('aria-required') === 'true') && !f.value)
          .map(f => f.name || f.getAttribute('aria-label') || f.type)
          .filter(Boolean)
      : [];

    const r = best.getBoundingClientRect();
    return {
      found:               true,
      tag:                 best.tagName.toLowerCase(),
      computedRole:        best.computedRole || best.getAttribute('role') || null,
      computedLabel:       best.computedLabel || best.getAttribute('aria-label') || null,
      disabled:            best.disabled || best.getAttribute('aria-disabled') === 'true',
      ariaExpanded:        best.getAttribute('aria-expanded'),
      visible:             cs.display !== 'none' && cs.visibility !== 'hidden',
      inViewport:          r.top >= 0 && r.bottom <= window.innerHeight,
      formMissingRequired: missingRequired,
      hint
    };
  }

  // ── Session planner (4B tool: plan_session) ────────────────────────────

  async function _planSession(screenshot) {
    const dom = _scanPage();
    return new Promise(resolve => {
      chrome.runtime.sendMessage(
        { action: 'planSession', goal: _goal, url: dom.url, title: dom.title, language: navigator.language || 'en', screenshot: screenshot || null },
        plan => {
          if (chrome.runtime.lastError || !Array.isArray(plan) || !plan.length) {
            resolve([]);
          } else {
            resolve(plan);
          }
        }
      );
    });
  }

  // ── Dot label — small text pill anchored next to the orange dot ─────────────

  function _setDotLabel(text) {
    let lbl = document.getElementById('ophelia-dot-label');
    if (!text) { lbl?.remove(); return; }
    if (!lbl) {
      lbl = document.createElement('div');
      lbl.id = 'ophelia-dot-label';
      lbl.style.cssText = [
        'position:fixed', 'z-index:2147483647', 'pointer-events:none',
        'background:rgba(9,9,13,0.88)',
        'color:#fff', 'font-size:11px', 'font-weight:500',
        'font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif',
        'padding:3px 9px', 'border-radius:9px', 'white-space:nowrap',
        'border:1px solid rgba(255,122,26,0.35)',
        'backdrop-filter:blur(6px)', '-webkit-backdrop-filter:blur(6px)'
      ].join(';');
      document.body.appendChild(lbl);
    }
    lbl.textContent = text;
    // Position: right of the orange dot if it exists, else bottom-center
    const dot = document.getElementById('ophelia-dot');
    if (dot) {
      const cx = parseFloat(dot.style.left) || 0; // dot center x
      const cy = parseFloat(dot.style.top)  || 0; // dot center y
      lbl.style.left      = `${cx + 16}px`;
      lbl.style.top       = `${cy - 10}px`;
      lbl.style.bottom    = 'auto';
      lbl.style.transform = 'none';
    } else {
      lbl.style.bottom    = '24px';
      lbl.style.left      = '50%';
      lbl.style.top       = 'auto';
      lbl.style.transform = 'translateX(-50%)';
    }
  }

  function _clearDotLabel() {
    document.getElementById('ophelia-dot-label')?.remove();
  }

  // ── TTS ─────────────────────────────────────────────────────────────────────

  function _speak(text, onEnd) {
    if (!window.speechSynthesis) { if (onEnd) onEnd(); return; }
    window.speechSynthesis.cancel();
    const utt = new SpeechSynthesisUtterance(text);
    if (onEnd) utt.onend = onEnd;
    utt.rate = _ttsRate; utt.pitch = 1.0; utt.volume = 1.0;
    utt.lang = navigator.language || 'en-US';
    const go = () => {
      const v    = window.speechSynthesis.getVoices();
      const pref = v.find(x => x.lang.startsWith('en') &&
                     (x.name.includes('Google') || x.name.includes('Samantha') || x.name.includes('Natural')))
                || v.find(x => x.lang.startsWith('en'));
      if (pref) utt.voice = pref;
      window.speechSynthesis.speak(utt);
    };
    window.speechSynthesis.getVoices().length ? go()
      : (window.speechSynthesis.onvoiceschanged = () => { window.speechSynthesis.onvoiceschanged = null; go(); });
  }

  function earlyInstruction(text) {
    if (text && _active) _speak(text);
  }

  return { activate, stop, isActive, checkResume, getAriaTree: _scanPage, inspectElement: _inspectElement, earlyInstruction };
})();
